-- TABLE
CREATE TABLE IF NOT EXISTS "OAUTH"."TB_USUARIO"
(
    "CD_USUARIO" BIGINT NOT NULL,
    "LOGIN" CHARACTER VARYING(60) NOT NULL,
    "EMAIL" CHARACTER VARYING(80) NOT NULL,
    "NOME" CHARACTER VARYING(100) NOT NULL,
    "HASH_SENHA" CHARACTER VARYING(60) NOT NULL,
    "DT_CADASTRO" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DT_ATUALIZACAO" TIMESTAMP WITH TIME ZONE,
    "CD_USUARIO_CRIACAO" BIGINT NOT NULL,
    "CD_USUARIO_ATUALIZACAO" BIGINT,
    "FL_ATIVO" BOOLEAN NOT NULL
);

-- COMMENT
COMMENT ON COLUMN "OAUTH"."TB_USUARIO"."CD_USUARIO" IS 'CÓDIGO DO USUÁRIO';
COMMENT ON COLUMN "OAUTH"."TB_USUARIO"."LOGIN" IS 'LOGIN DO USUÁRIO';
COMMENT ON COLUMN "OAUTH"."TB_USUARIO"."EMAIL" IS 'E-MAIL DO USUÁRIO';
COMMENT ON COLUMN "OAUTH"."TB_USUARIO"."NOME" IS 'NOME DO USUÁRIO';
COMMENT ON COLUMN "OAUTH"."TB_USUARIO"."HASH_SENHA" IS 'HASH DA SENHA DO USUÁRIO';
COMMENT ON COLUMN "OAUTH"."TB_USUARIO"."DT_CADASTRO" IS 'DATA DE CADASTRO DO USUÁRIO';
COMMENT ON COLUMN "OAUTH"."TB_USUARIO"."DT_ATUALIZACAO" IS 'DATA DE ATUALIZAÇÃO DO USUÁRIO';
COMMENT ON COLUMN "OAUTH"."TB_USUARIO"."CD_USUARIO_CRIACAO" IS 'USUÁRIO DE CRIAÇÃO DO USUÁRIO';
COMMENT ON COLUMN "OAUTH"."TB_USUARIO"."CD_USUARIO_ATUALIZACAO" IS 'USUÁRIO DE ATUALIZAÇÃO DO USUÁRIO';
COMMENT ON COLUMN "OAUTH"."TB_USUARIO"."FL_ATIVO" IS '[TRUE/FALSE] - SINALIZAÇÃO DE ATIVO DO USUÁRIO';

-- PRIMARY KEY 
ALTER TABLE "OAUTH"."TB_USUARIO" ADD CONSTRAINT "PK_TB_USUARIO" PRIMARY KEY ("CD_USUARIO");

-- UNIQUE KEY 
ALTER TABLE "OAUTH"."TB_USUARIO" ADD CONSTRAINT "UK_LOGIN" UNIQUE ("LOGIN");
ALTER TABLE "OAUTH"."TB_USUARIO" ADD CONSTRAINT "UK_EMAIL" UNIQUE ("EMAIL");

