-- TABLE
CREATE TABLE IF NOT EXISTS "OAUTH"."TB_GRUPO"
(
    "CD_GRUPO" BIGINT NOT NULL,
    "NOME" CHARACTER VARYING(100) NOT NULL,
    "DESCRICAO" CHARACTER VARYING(100) NOT NULL,
    "DT_CADASTRO" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DT_ATUALIZACAO" TIMESTAMP WITH TIME ZONE,
    "CD_USUARIO_CRIACAO" BIGINT NOT NULL,
    "CD_USUARIO_ATUALIZACAO" BIGINT,
    "FL_ATIVO" BOOLEAN NOT NULL
);

-- COMMENT
COMMENT ON COLUMN "OAUTH"."TB_GRUPO"."CD_GRUPO" IS 'CÓDIGO DO GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_GRUPO"."NOME" IS 'NOME DO GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_GRUPO"."DESCRICAO" IS 'DESCRIÇÃO DO GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_GRUPO"."DT_CADASTRO" IS 'DATA DE CADASTRO DO GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_GRUPO"."DT_ATUALIZACAO" IS 'DATA DE ATUALIZAÇÃO DO GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_GRUPO"."CD_USUARIO_CRIACAO" IS 'USUÁRIO DE CRIAÇÃO DO GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_GRUPO"."CD_USUARIO_ATUALIZACAO" IS 'USUÁRIO DE ATUALIZAÇÃO DO GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_GRUPO"."FL_ATIVO" IS '[TRUE/FALSE] - SINALIZAÇÃO DE ATIVO DO GRUPO';

-- PRIMARY KEY 
ALTER TABLE "OAUTH"."TB_GRUPO" ADD CONSTRAINT "PK_TB_GRUPO" PRIMARY KEY ("CD_GRUPO");

-- UNIQUE KEY 
ALTER TABLE "OAUTH"."TB_GRUPO" ADD CONSTRAINT "UK_NOME_TB_GRUPO" UNIQUE ("NOME");

-- FOREIGN KEY
ALTER TABLE "OAUTH"."TB_GRUPO" ADD CONSTRAINT "FK_GA_TB_USUARIO" FOREIGN KEY ("CD_USUARIO_CRIACAO") REFERENCES "OAUTH"."TB_USUARIO" ("CD_USUARIO");
ALTER TABLE "OAUTH"."TB_GRUPO" ADD CONSTRAINT "FK_GB_TB_USUARIO" FOREIGN KEY ("CD_USUARIO_ATUALIZACAO") REFERENCES "OAUTH"."TB_USUARIO" ("CD_USUARIO"); 

