-- TABLE
CREATE TABLE IF NOT EXISTS "OAUTH"."TB_APLICACAO"
(
    "CD_APLICACAO" BIGINT NOT NULL,
    "NOME" CHARACTER VARYING(100) NOT NULL,
    "DESCRICAO" CHARACTER VARYING(100) NOT NULL,
    "DT_CADASTRO" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DT_ATUALIZACAO" TIMESTAMP WITH TIME ZONE,
    "CD_USUARIO_CRIACAO" BIGINT NOT NULL,
    "CD_USUARIO_ATUALIZACAO" BIGINT,
    "FL_ATIVA" BOOLEAN NOT NULL,
    "TP_APLICACAO" CHARACTER VARYING(80) NOT NULL,
    "SEGREDO" CHARACTER VARYING(100) NOT NULL,
    "FL_SEGURANCA" BOOLEAN NOT NULL,
    "TMP_ACCESS_TOKEN" INTEGER NOT NULL,
    "TMP_REFRESH_TOKEN" INTEGER,
    "FL_REFRESH_TOKEN" BOOLEAN NOT NULL
);

-- COMMENT
COMMENT ON COLUMN "OAUTH"."TB_APLICACAO"."CD_APLICACAO" IS 'CÓDIGO DA APLICAÇÃO';
COMMENT ON COLUMN "OAUTH"."TB_APLICACAO"."NOME" IS 'NOME DA APLICAÇÃO';
COMMENT ON COLUMN "OAUTH"."TB_APLICACAO"."DESCRICAO" IS 'DESCRIÇÃO DA APLICAÇÃO';
COMMENT ON COLUMN "OAUTH"."TB_APLICACAO"."DT_CADASTRO" IS 'DATA DE CADASTRO DA APLICAÇÃO';
COMMENT ON COLUMN "OAUTH"."TB_APLICACAO"."DT_ATUALIZACAO" IS 'DATA DE ATUALIZAÇÃO DA APLICAÇÃO';
COMMENT ON COLUMN "OAUTH"."TB_APLICACAO"."CD_USUARIO_CRIACAO" IS 'USUÁRIO DE CRIAÇÃO DA APLICAÇÃO';
COMMENT ON COLUMN "OAUTH"."TB_APLICACAO"."CD_USUARIO_ATUALIZACAO" IS 'USUÁRIO DE ATUALIZAÇÃO DA APLICAÇÃO';
COMMENT ON COLUMN "OAUTH"."TB_APLICACAO"."FL_ATIVA" IS '[TRUE/FALSE] - SINALIZAÇÃO DE ATIVA DA APLICAÇÃO';
COMMENT ON COLUMN "OAUTH"."TB_APLICACAO"."SEGREDO" IS 'SEGREDO DA APLICAÇÃO';
COMMENT ON COLUMN "OAUTH"."TB_APLICACAO"."FL_SEGURANCA" IS '[TRUE/FALSE] - SINALIZAÇÃO DE SEGURANÇA DA APLICAÇÃO';
COMMENT ON COLUMN "OAUTH"."TB_APLICACAO"."TMP_ACCESS_TOKEN" IS 'TEMPO DE VALIDADE DO ACCESS TOKEN DA APLICAÇÃO';
COMMENT ON COLUMN "OAUTH"."TB_APLICACAO"."TMP_REFRESH_TOKEN" IS 'TEMPO DE VALIDADE DO REFRESH TOKEN DA APLICAÇÃO';
COMMENT ON COLUMN "OAUTH"."TB_APLICACAO"."FL_REFRESH_TOKEN" IS '[TRUE/FALSE] - SINALIZAÇÃO DE REFRESH TOKEN DA APLICAÇÃO';

-- PRIMARY KEY 
ALTER TABLE "OAUTH"."TB_APLICACAO" ADD CONSTRAINT "PK_TB_APLICACAO" PRIMARY KEY ("CD_APLICACAO");

-- UNIQUE KEY 
ALTER TABLE "OAUTH"."TB_APLICACAO" ADD CONSTRAINT "UK_NOME_TB_APLICACAO" UNIQUE ("NOME");

-- FOREIGN KEY
ALTER TABLE "OAUTH"."TB_APLICACAO" ADD CONSTRAINT "FK_PA_TB_USUARIO" FOREIGN KEY ("CD_USUARIO_CRIACAO") REFERENCES "OAUTH"."TB_USUARIO" ("CD_USUARIO");
ALTER TABLE "OAUTH"."TB_APLICACAO" ADD CONSTRAINT "FK_PB_TB_USUARIO" FOREIGN KEY ("CD_USUARIO_ATUALIZACAO") REFERENCES "OAUTH"."TB_USUARIO" ("CD_USUARIO"); 

