-- TABLE
CREATE TABLE IF NOT EXISTS "OAUTH"."TB_PERMISSAO"
(
    "CD_PERMISSAO" BIGINT NOT NULL,
    "NOME" CHARACTER VARYING(100) NOT NULL,
    "DESCRICAO" CHARACTER VARYING(100) NOT NULL,
    "DT_CADASTRO" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DT_ATUALIZACAO" TIMESTAMP WITH TIME ZONE,
    "CD_APLICACAO" BIGINT NOT NULL,
    "CD_USUARIO_CRIACAO" BIGINT NOT NULL,
    "CD_USUARIO_ATUALIZACAO" BIGINT,
    "FL_ATIVA" BOOLEAN NOT NULL
);

-- COMMENT
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO"."CD_PERMISSAO" IS 'CÓDIGO DA PERMISSÃO';
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO"."NOME" IS 'NOME DA PERMISSÃO';
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO"."DESCRICAO" IS 'DESCRIÇÃO DA PERMISSÃO';
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO"."DT_CADASTRO" IS 'DATA DE CADASTRO DA PERMISSÃO';
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO"."DT_ATUALIZACAO" IS 'DATA DE ATUALIZAÇÃO DA PERMISSÃO';
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO"."CD_APLICACAO" IS 'CÓDIGO DA APLICAÇÃO DA PERMISSÃO';
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO"."CD_USUARIO_CRIACAO" IS 'CÓDIGO DO USUÁRIO DE CRIAÇÃO DA PERMISSÃO';
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO"."CD_USUARIO_ATUALIZACAO" IS 'CÓDIGO DO USUÁRIO DE ATUALIZAÇÃO DA PERMISSÃO';
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO"."FL_ATIVA" IS '[TRUE/FALSE] - SINALIZAÇÃO DE ATIVA DA PERMISSÃO';

-- PRIMARY KEY 
ALTER TABLE "OAUTH"."TB_PERMISSAO" ADD CONSTRAINT "PK_TB_PERMISSAO" PRIMARY KEY ("CD_PERMISSAO");

-- UNIQUE KEY 
ALTER TABLE "OAUTH"."TB_PERMISSAO" ADD CONSTRAINT "UK_NCA_TB_PERMISSAO" UNIQUE ("NOME", "CD_APLICACAO");

-- FOREIGN KEY
ALTER TABLE "OAUTH"."TB_PERMISSAO" ADD CONSTRAINT "FK_PA_TB_APLICACAO" FOREIGN KEY ("CD_APLICACAO") REFERENCES "OAUTH"."TB_APLICACAO" ("CD_APLICACAO");
ALTER TABLE "OAUTH"."TB_PERMISSAO" ADD CONSTRAINT "FK_PB_TB_USUARIO" FOREIGN KEY ("CD_USUARIO_CRIACAO") REFERENCES "OAUTH"."TB_USUARIO" ("CD_USUARIO");
ALTER TABLE "OAUTH"."TB_PERMISSAO" ADD CONSTRAINT "FK_PC_TB_USUARIO" FOREIGN KEY ("CD_USUARIO_ATUALIZACAO") REFERENCES "OAUTH"."TB_USUARIO" ("CD_USUARIO"); 

