-- TABLE
CREATE TABLE IF NOT EXISTS "OAUTH"."TB_PERMISSAO_GRUPO"
(
	"CD_PERMISSAO" BIGINT NOT NULL,
    "CD_GRUPO" BIGINT NOT NULL,
    "DT_CADASTRO" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DT_ATUALIZACAO" TIMESTAMP WITH TIME ZONE,
    "CD_USUARIO_CRIACAO" BIGINT NOT NULL,
    "CD_USUARIO_ATUALIZACAO" BIGINT,
    "FL_ATIVA" BOOLEAN NOT NULL
);

-- COMMENT
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO_GRUPO"."CD_PERMISSAO" IS 'CÓDIGO DA PERMISSÃO DA PERMISSÃO GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO_GRUPO"."CD_GRUPO" IS 'CÓDIGO DO GRUPO DA PERMISSÃO GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO_GRUPO"."DT_CADASTRO" IS 'DATA DE CADASTRO DA PERMISSÃO GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO_GRUPO"."DT_ATUALIZACAO" IS 'DATA DE ATUALIZAÇÃO DA PERMISSÃO GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO_GRUPO"."CD_USUARIO_CRIACAO" IS 'USUÁRIO DE CRIAÇÃO DA PERMISSÃO GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO_GRUPO"."CD_USUARIO_ATUALIZACAO" IS 'USUÁRIO DE ATUALIZAÇÃO DA PERMISSÃO GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_PERMISSAO_GRUPO"."FL_ATIVA" IS '[TRUE/FALSE] - SINALIZAÇÃO DE ATIVA DA PERMISSÃO GRUPO';

-- PRIMARY KEY 
ALTER TABLE "OAUTH"."TB_PERMISSAO_GRUPO" ADD CONSTRAINT "PK_TB_PERMISSAO_GRUPO" PRIMARY KEY ("CD_PERMISSAO", "CD_GRUPO");

-- FOREIGN KEY
ALTER TABLE "OAUTH"."TB_PERMISSAO_GRUPO" ADD CONSTRAINT "FK_PGB_TB_PERMISSAO_GRUPO" FOREIGN KEY ("CD_PERMISSAO") REFERENCES "OAUTH"."TB_PERMISSAO" ("CD_PERMISSAO"); 
ALTER TABLE "OAUTH"."TB_PERMISSAO_GRUPO" ADD CONSTRAINT "FK_PGA_TB_PERMISSAO_GRUPO" FOREIGN KEY ("CD_GRUPO") REFERENCES "OAUTH"."TB_GRUPO" ("CD_GRUPO");
ALTER TABLE "OAUTH"."TB_PERMISSAO_GRUPO" ADD CONSTRAINT "FK_PGC_TB_PERMISSAO_GRUPO" FOREIGN KEY ("CD_USUARIO_CRIACAO") REFERENCES "OAUTH"."TB_USUARIO" ("CD_USUARIO");
ALTER TABLE "OAUTH"."TB_PERMISSAO_GRUPO" ADD CONSTRAINT "FK_PGD_TB_PERMISSAO_GRUPO" FOREIGN KEY ("CD_USUARIO_ATUALIZACAO") REFERENCES "OAUTH"."TB_USUARIO" ("CD_USUARIO"); 

