-- TABLE
CREATE TABLE IF NOT EXISTS "OAUTH"."TB_ROTA_GRUPO"
(
	"CD_ROTA" BIGINT NOT NULL,
    "CD_GRUPO" BIGINT NOT NULL,
    "DT_CADASTRO" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DT_ATUALIZACAO" TIMESTAMP WITH TIME ZONE,
    "CD_USUARIO_CRIACAO" BIGINT NOT NULL,
    "CD_USUARIO_ATUALIZACAO" BIGINT,
    "FL_ATIVA" BOOLEAN NOT NULL
);

-- COMMENT
COMMENT ON COLUMN "OAUTH"."TB_ROTA_GRUPO"."CD_ROTA" IS 'CÓDIGO DA ROTA DA ROTA GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_ROTA_GRUPO"."CD_GRUPO" IS 'CÓDIGO DO GRUPO DA ROTA GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_ROTA_GRUPO"."DT_CADASTRO" IS 'DATA DE CADASTRO DA ROTA GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_ROTA_GRUPO"."DT_ATUALIZACAO" IS 'DATA DE ATUALIZAÇÃO DA ROTA GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_ROTA_GRUPO"."CD_USUARIO_CRIACAO" IS 'USUÁRIO DE CRIAÇÃO DA ROTA GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_ROTA_GRUPO"."CD_USUARIO_ATUALIZACAO" IS 'USUÁRIO DE ATUALIZAÇÃO DA ROTA GRUPO';
COMMENT ON COLUMN "OAUTH"."TB_ROTA_GRUPO"."FL_ATIVA" IS '[TRUE/FALSE] - SINALIZAÇÃO DE ATIVA DA ROTA GRUPO';

-- PRIMARY KEY 
ALTER TABLE "OAUTH"."TB_ROTA_GRUPO" ADD CONSTRAINT "PK_TB_ROTA_GRUPO" PRIMARY KEY ("CD_ROTA", "CD_GRUPO");

-- FOREIGN KEY
ALTER TABLE "OAUTH"."TB_ROTA_GRUPO" ADD CONSTRAINT "FK_RGB_TB_ROTA_GRUPO" FOREIGN KEY ("CD_ROTA") REFERENCES "OAUTH"."TB_ROTA" ("CD_ROTA"); 
ALTER TABLE "OAUTH"."TB_ROTA_GRUPO" ADD CONSTRAINT "FK_RGA_TB_ROTA_GRUPO" FOREIGN KEY ("CD_GRUPO") REFERENCES "OAUTH"."TB_GRUPO" ("CD_GRUPO");
ALTER TABLE "OAUTH"."TB_ROTA_GRUPO" ADD CONSTRAINT "FK_RGC_TB_ROTA_GRUPO" FOREIGN KEY ("CD_USUARIO_CRIACAO") REFERENCES "OAUTH"."TB_USUARIO" ("CD_USUARIO");
ALTER TABLE "OAUTH"."TB_ROTA_GRUPO" ADD CONSTRAINT "FK_RGD_TB_ROTA_GRUPO" FOREIGN KEY ("CD_USUARIO_ATUALIZACAO") REFERENCES "OAUTH"."TB_USUARIO" ("CD_USUARIO"); 

