-- TABLE
CREATE TABLE IF NOT EXISTS "OAUTH"."TB_ESCOPO"
(
    "CD_ESCOPO" BIGINT NOT NULL,
    "NOME" CHARACTER VARYING(100) NOT NULL,
    "DESCRICAO" CHARACTER VARYING(100) NOT NULL,
    "DT_CADASTRO" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DT_ATUALIZACAO" TIMESTAMP WITH TIME ZONE,
    "CD_APLICACAO" BIGINT NOT NULL,
    "CD_USUARIO_CRIACAO" BIGINT NOT NULL,
    "CD_USUARIO_ATUALIZACAO" BIGINT,
    "FL_ATIVO" BOOLEAN NOT NULL
);

-- COMMENT
COMMENT ON COLUMN "OAUTH"."TB_ESCOPO"."CD_ESCOPO" IS 'CÓDIGO DO ESCOPO';
COMMENT ON COLUMN "OAUTH"."TB_ESCOPO"."NOME" IS 'NOME DO ESCOPO';
COMMENT ON COLUMN "OAUTH"."TB_ESCOPO"."DESCRICAO" IS 'DESCRIÇÃO DO ESCOPO';
COMMENT ON COLUMN "OAUTH"."TB_ESCOPO"."DT_CADASTRO" IS 'DATA DE CADASTRO DO ESCOPO';
COMMENT ON COLUMN "OAUTH"."TB_ESCOPO"."DT_ATUALIZACAO" IS 'DATA DE ATUALIZAÇÃO DO ESCOPO';
COMMENT ON COLUMN "OAUTH"."TB_ESCOPO"."CD_APLICACAO" IS 'CÓDIGO DA APLICAÇÃO DO ESCOPO';
COMMENT ON COLUMN "OAUTH"."TB_ESCOPO"."CD_USUARIO_CRIACAO" IS 'CÓDIGO DO USUÁRIO DE CRIAÇÃO DO ESCOPO';
COMMENT ON COLUMN "OAUTH"."TB_ESCOPO"."CD_USUARIO_ATUALIZACAO" IS 'CÓDIGO DO USUÁRIO DE ATUALIZAÇÃO DO ESCOPO';
COMMENT ON COLUMN "OAUTH"."TB_ESCOPO"."FL_ATIVO" IS '[TRUE/FALSE] - SINALIZAÇÃO DE ATIVO DO ESCOPO';

-- PRIMARY KEY 
ALTER TABLE "OAUTH"."TB_ESCOPO" ADD CONSTRAINT "PK_TB_ESCOPO" PRIMARY KEY ("CD_ESCOPO");

-- UNIQUE KEY 
ALTER TABLE "OAUTH"."TB_ESCOPO" ADD CONSTRAINT "UK_NCA_TB_ESCOPO" UNIQUE ("NOME", "CD_APLICACAO");

-- FOREIGN KEY
ALTER TABLE "OAUTH"."TB_ESCOPO" ADD CONSTRAINT "FK_EA_TB_APLICACAO" FOREIGN KEY ("CD_APLICACAO") REFERENCES "OAUTH"."TB_APLICACAO" ("CD_APLICACAO");
ALTER TABLE "OAUTH"."TB_ESCOPO" ADD CONSTRAINT "FK_EB_TB_USUARIO" FOREIGN KEY ("CD_USUARIO_CRIACAO") REFERENCES "OAUTH"."TB_USUARIO" ("CD_USUARIO");
ALTER TABLE "OAUTH"."TB_ESCOPO" ADD CONSTRAINT "FK_EC_TB_USUARIO" FOREIGN KEY ("CD_USUARIO_ATUALIZACAO") REFERENCES "OAUTH"."TB_USUARIO" ("CD_USUARIO"); 

