-- TABLE
CREATE TABLE IF NOT EXISTS "OAUTH"."TB_RECURSO"
(
    "CD_RECURSO" BIGINT NOT NULL,
    "NOME" CHARACTER VARYING(100) NOT NULL,
    "DESCRICAO" CHARACTER VARYING(100) NOT NULL,
    "DT_CADASTRO" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DT_ATUALIZACAO" TIMESTAMP WITH TIME ZONE,
    "CD_APLICACAO" BIGINT NOT NULL,
    "CD_USUARIO_CRIACAO" BIGINT NOT NULL,
    "CD_USUARIO_ATUALIZACAO" BIGINT,
    "FL_ATIVO" BOOLEAN NOT NULL
);

-- COMMENT
COMMENT ON COLUMN "OAUTH"."TB_RECURSO"."CD_RECURSO" IS 'CÓDIGO DO RECURSO';
COMMENT ON COLUMN "OAUTH"."TB_RECURSO"."NOME" IS 'NOME DO RECURSO';
COMMENT ON COLUMN "OAUTH"."TB_RECURSO"."DESCRICAO" IS 'DESCRIÇÃO DO RECURSO';
COMMENT ON COLUMN "OAUTH"."TB_RECURSO"."DT_CADASTRO" IS 'DATA DE CADASTRO DO RECURSO';
COMMENT ON COLUMN "OAUTH"."TB_RECURSO"."DT_ATUALIZACAO" IS 'DATA DE ATUALIZAÇÃO DO RECURSO';
COMMENT ON COLUMN "OAUTH"."TB_RECURSO"."CD_APLICACAO" IS 'CÓDIGO DA APLICAÇÃO DO RECURSO';
COMMENT ON COLUMN "OAUTH"."TB_RECURSO"."CD_USUARIO_CRIACAO" IS 'CÓDIGO DO USUÁRIO DE CRIAÇÃO DO RECURSO';
COMMENT ON COLUMN "OAUTH"."TB_RECURSO"."CD_USUARIO_ATUALIZACAO" IS 'CÓDIGO DO USUÁRIO DE ATUALIZAÇÃO DO RECURSO';
COMMENT ON COLUMN "OAUTH"."TB_RECURSO"."FL_ATIVO" IS '[TRUE/FALSE] - SINALIZAÇÃO DE ATIVO DO RECURSO';

-- PRIMARY KEY 
ALTER TABLE "OAUTH"."TB_RECURSO" ADD CONSTRAINT "PK_TB_RECURSO" PRIMARY KEY ("CD_RECURSO");

-- UNIQUE KEY 
ALTER TABLE "OAUTH"."TB_RECURSO" ADD CONSTRAINT "UK_NCA_TB_RECURSO" UNIQUE ("NOME", "CD_APLICACAO");

-- FOREIGN KEY
ALTER TABLE "OAUTH"."TB_RECURSO" ADD CONSTRAINT "FK_RA_TB_APLICACAO" FOREIGN KEY ("CD_APLICACAO") REFERENCES "OAUTH"."TB_APLICACAO" ("CD_APLICACAO");
ALTER TABLE "OAUTH"."TB_RECURSO" ADD CONSTRAINT "FK_RB_TB_USUARIO" FOREIGN KEY ("CD_USUARIO_CRIACAO") REFERENCES "OAUTH"."TB_USUARIO" ("CD_USUARIO");
ALTER TABLE "OAUTH"."TB_RECURSO" ADD CONSTRAINT "FK_RC_TB_USUARIO" FOREIGN KEY ("CD_USUARIO_ATUALIZACAO") REFERENCES "OAUTH"."TB_USUARIO" ("CD_USUARIO"); 

